### ISSUE TITLE
Not using full power

### ISSUE THREAD

**Issue by theprodigy221121** [Lambda11/pet-skill-replacer-and-user#7]
So I want want 20 Power instead of 40, what line should I edit exactly if it is even possible to do that

**Comment by Zezo12345** [comment]
Not sure i haven't tried it. It would be a nice feature for people that want to have it but this mod is like really good already. Although maybe if you use a number between ((event.skill >= 1101 && event.skill < 1138) , where 1138 is the 40 power buff and open config.json and replace "NewPartnerAbility": 1138 to somewhere between 1101-1138 and test and type here if this works :)
